gfx/env/robobk.tga
gfx/env/robodn.tga
gfx/env/roboft.tga
gfx/env/robolf.tga
gfx/env/robort.tga
gfx/env/roboup.tga
sound/endplayer_s/amb_factory2.wav
sound/endplayer_s/amb_factorys.wav
sound/endplayer_s/beat.wav
sound/endplayer_s/comp_works4.wav
sound/endplayer_s/electr.wav
sound/endplayer_s/fence2.wav
sound/endplayer_s/helicopter1.wav
sound/endplayer_s/helicopter2.wav
sound/endplayer_s/jetthr.wav
sound/endplayer_s/kustthrough.wav
sound/endplayer_s/machine.wav
sound/endplayer_s/main_windloop.wav
sound/endplayer_s/sewer_drip.wav
sound/endplayer_s/strong_wind.wav
sound/endplayer_s/water_noise.wav
models/endplayer_m/barricade.mdl
models/endplayer_m/bush.mdl
models/endplayer_m/chair1.mdl
models/endplayer_m/dumpster.mdl
models/endplayer_m/electrix.mdl
models/endplayer_m/fence.mdl
models/endplayer_m/headless_zombie.mdl
models/endplayer_m/trash1.mdl
models/endplayer_m/trash2.mdl
models/endplayer_m/tree_noleaves.mdl
maps/8th_battleground.res
