sound/unearth/amb01.wav
sound/techno/backgrnd.wav
maps/catacomb.bsp
maps/catacomb.txt
maps/catacomb.res
sprites/colflare.spr
sound/techno/ds9ops.wav
sound/ambience/fluorescent.wav
sound/ambience/lv_neon.wav
sound/moon1.wav
gfx/env/null_hills3-256_bk.tga
gfx/env/null_hills3-256_dn.tga
gfx/env/null_hills3-256_ft.tga
gfx/env/null_hills3-256_lf.tga
gfx/env/null_hills3-256_rt.tga
gfx/env/null_hills3-256_up.tga
sound/techno/raspy.wav
sound/unearth/Reactor.wav
