maps/dm_achluophobia_b1.bsp
maps/dm_achluophobia_b1.res
sprites/tunnelrats/xsmoke4_fix.spr
sprites/tunnelrats/xsmoke4_fix_flip.spr
sprites/tunnelrats/xssmke1_fix.spr
sound/dm_achluophobia/dripping.wav
sound/dm_achluophobia/emdrill.wav
sound/dm_achluophobia/eng.wav
sound/dm_achluophobia/fan2.wav
sound/dm_achluophobia/bb.wav
sound/dm_achluophobia/bf.wav
sound/dm_achluophobia/lowsteam.wav
sound/dm_achluophobia/mech_amb1.wav
sound/dm_achluophobia/metal5.wav
sound/dm_achluophobia/rumblewhine.wav
sound/dm_achluophobia/shaft.wav
sound/dm_achluophobia/steam1.wav
sound/dm_achluophobia/metal9.wav
sound/dm_achluophobia/p-groan3.wav
sound/dm_achluophobia/steamburst4.wav
sound/dm_achluophobia/vent_scurry_medium.wav
sound/dm_achluophobia/turbine.wav
