maps/dm_shafted_final.bsp
maps/dm_shafted_final.res
sprites/shafted/cavein.spr
sprites/shafted/cavein2.spr
sound/dm_shafted/bigfastfan.wav
sound/dm_shafted/creakywood1.wav
sound/dm_shafted/creakymetal1.wav
sound/dm_shafted/fan_squeaky.wav
sound/dm_shafted/fan_squeaky2.wav
sound/dm_shafted/cavewind.wav
sound/dm_shafted/quake1.wav
sound/dm_shafted/elevator_ring.wav
sound/dm_shafted/rocks/rocks1.wav
sound/dm_shafted/rocks/rocks2.wav
sound/dm_shafted/rocks/rocks3.wav
sound/dm_shafted/rocks/rocks4.wav
sound/dm_shafted/rocks/rocks5.wav
sound/dm_shafted/rocks/rocks6.wav