maps/dm_tropic.txt
tropic.wad
gfx/env/sky_fppbk.tga
gfx/env/sky_fppdn.tga
gfx/env/sky_fppft.tga
gfx/env/sky_fpplf.tga
gfx/env/sky_fpprt.tga
gfx/env/sky_fppup.tga
models/dm_tropic/palmy/driftwood_01a.mdl
models/dm_tropic/palmy/gianttree01.mdl
models/dm_tropic/palmy/kokosovnik2.mdl
models/dm_tropic/palmy/kokosovnik3.mdl
models/dm_tropic/palmy/palmabanan.mdl
models/dm_tropic/palmy/pearpalm.mdl
models/dm_tropic/palmy/pearpalmb.mdl
models/dm_tropic/palmy/rock_riverbed01a.mdl
models/dm_tropic/palmy/rock_riverbed01b.mdl
models/dm_tropic/palmy/rock_riverbed01d.mdl
models/dm_tropic/palmy/rock_riverbed02b.mdl
models/dm_tropic/palmy/rock11.mdl
models/dm_tropic/palmy/rock13.mdl
models/dm_tropic/palmy/rock14.mdl
models/dm_tropic/palmy/rock15.mdl
models/dm_tropic/palmy/rockcliff_cluster01b.mdl
models/dm_tropic/palmy/rockcliff_cluster02a.mdl
models/dm_tropic/palmy/rockcliff_cluster02b.mdl
models/dm_tropic/palmy/rockcliff_cluster02c.mdl
models/dm_tropic/palmy/rockcliff_cluster03c.mdl
models/dm_tropic/palmy/rockgranite04a.mdl
models/dm_tropic/palmy/rockgranite04b.mdl
models/dm_tropic/palmy/rockgranite04c.mdl
models/dm_tropic/palmy/tree04.mdl
models/dm_tropic/palmy/tree05.mdl
models/dm_tropic/palmy/tree06.mdl
models/dm_tropic/palmy/tropic02.mdl
models/dm_tropic/palmy/tropic03.mdl
models/dm_tropic/structure/ammo_can_02.mdl
models/dm_tropic/structure/boat_fishing01a.mdl
models/dm_tropic/structure/boat001a.mdl
models/dm_tropic/structure/boat001b.mdl
models/dm_tropic/structure/boat002b.mdl
models/dm_tropic/structure/dock_broken01a_256.mdl
models/dm_tropic/structure/dock01_polecluster01d_256.mdl
models/dm_tropic/structure/merge_banc.mdl
models/dm_tropic/structure/merge_bateau.mdl
models/dm_tropic/structure/merge_hangar.mdl
models/dm_tropic/structure/merge_maison.mdl
models/dm_tropic/structure/merge_passage.mdl
models/dm_tropic/structure/merge_pont.mdl
models/dm_tropic/structure/merge_ponton.mdl
models/dm_tropic/structure/merge_relai.mdl
models/dm_tropic/structure/merge_relai2.mdl
models/dm_tropic/structure/merge_relai3.mdl
models/dm_tropic/structure/merge_tente.mdl
models/dm_tropic/structure/metal_panel02a.mdl
sound/dm_tropic/bird1.wav
sound/dm_tropic/bird2.wav
sound/dm_tropic/coastbird1.wav
sound/dm_tropic/lake_water.wav
sound/dm_tropic/lightwind.wav
sound/dm_tropic/oceanloop_quiet.wav
sound/dm_tropic/seagull_idle1.wav
sound/dm_tropic/seagull_idle2.wav
sound/dm_tropic/seagulls_ambient1.wav
sound/dm_tropic/swamp_bird1.wav
sound/dm_tropic/swamp_bird3.wav
sound/dm_tropic/swamp_bird4.wav
sound/dm_tropic/water_oceanwavebreak1.wav
sound/dm_tropic/water_oceanwavebreak2.wav
sound/dm_tropic/water_oceanwavebreak3.wav
sound/dm_tropic/water_oceanwavebreak4.wav