
gfx/env/city_daybk.tga
gfx/env/city_daydn.tga
gfx/env/city_dayft.tga
gfx/env/city_daylf.tga
gfx/env/city_dayrt.tga
gfx/env/city_dayup.tga
gfx/detail/pshopd_01.tga
gfx/detail/pshopd_09.tga
gfx/detail/pshopd_10.tga
//models/jinx/couch1.mdl
//models/jinx/xen_plant1.mdl
//models/jinx/xen_plant4.mdl
//models/jinx/xen_plant8.mdl
//models/jinx/w_grenade.mdl
models/jinx/w_grenadet.mdl
//models/jinx/xen_models.txt
//maps/hldm_museum.bsp
maps/hldm_museum.res
maps/hldm_museum.txt
maps/hldm_museum_detail.txt
maps/hldm_museum_README.txt
