sound/minophor/accept1.wav
sound/minophor/accept2.wav
sound/minophor/accept3.wav
sound/minophor/accept4.wav
sound/minophor/amb_air.wav
sound/minophor/amb_beat1.wav
sound/minophor/amb_machinery.wav
sound/minophor/amb_noise.wav
sound/minophor/bomb.wav
sound/minophor/comp_works.wav
sound/minophor/comp_works1.wav
sound/minophor/comp_works3.wav
sound/minophor/comp_works4.wav
sound/minophor/denied.wav
sound/minophor/doorclosed.wav
sound/minophor/electricity.wav
sound/minophor/engine.wav
sound/minophor/fanutheunseen.wav
sound/minophor/generator_work.wav
sound/minophor/metal_str1.wav
sound/minophor/metal_str2.wav
sound/minophor/metal_str3_large.wav
sound/minophor/monster_reaction.wav
sound/minophor/sewer_drip.wav
sound/minophor/siren_tri.wav
sound/minophor/sp_fense.wav
sound/minophor/sp_waterfall1.wav
sound/minophor/squeak.wav
sound/minophor/steam_release.wav
maps/minophor.res