gfx/env/monoup.tga
gfx/env/monodn.tga
gfx/env/monolf.tga
gfx/env/monort.tga
gfx/env/monoft.tga
gfx/env/monobk.tga
sound/monorail/engine
sound/monorail/helicopter1
sound/monorail/helicopter2
sound/monorail/jet1
sound/monorail/jet2
sound/monorail/sp_fense
sound/monorail/sp_waterfall1
sound/monorail/sp_windloop
sound/monorail/winddd
models/monorail/bush1.mdl
models/monorail/bush2.mdl
models/monorail/bush3.mdl
models/monorail/dolly.mdl
models/monorail/fire_extinguisher.mdl
models/monorail/generator.mdl
models/monorail/lab_oscilliscope.mdl
models/monorail/sink_small.mdl
models/monorail/toilet_dirty.mdl
models/monorail/trash_trashcan.mdl
models/monorail/tree_noleaves.mdl
maps/mono.res