maps/multy_mod.txt
models/multy_mod/tree3.mdl
globo.wad
madeath.wad
gfx/env/multy_skybk.tga
gfx/env/multy_skydn.tga
gfx/env/multy_skyft.tga
gfx/env/multy_skylf.tga
gfx/env/multy_skyrt.tga
gfx/env/multy_skyup.tga
sound/multy_mod/ns_bastturbine.wav
sound/multy_mod/ns_pulsingwhine.wav
sound/multy_mod/ns_turbine.wav
sprites/animglow01_ma.spr
sprites/bolte1.spr
sprites/jinx_fog.spr
sprites/multy_hud_set.spr
