gfx/env/cm-thosemntns256_bk.tga
gfx/env/cm-thosemntns256_dn.tga
gfx/env/cm-thosemntns256_ft.tga
gfx/env/cm-thosemntns256_lf.tga
gfx/env/cm-thosemntns256_rt.tga
gfx/env/cm-thosemntns256_up.tga
//gfx/env/cm-thosemntns256_bk.bmp
//gfx/env/cm-thosemntns256_dn.bmp
//gfx/env/cm-thosemntns256_ft.bmp
//gfx/env/cm-thosemntns256_lf.bmp
//gfx/env/cm-thosemntns256_rt.bmp
//gfx/env/cm-thosemntns256_up.bmp
models/gulch/plant_palm.mdl
models/gulch/skeleton2.mdl