unearth.wad
//maps/unearth.bsp
maps/unearth.txt
sound/Unearth/alien_squit2.wav
sound/Unearth/Amb01.wav
sound/Unearth/Engine.wav
sound/Unearth/Error.wav
sound/Unearth/Fart2.wav
sound/Unearth/Reactor.wav
gfx/env/whirlpool_bk.tga
gfx/env/whirlpool_dn.tga
gfx/env/whirlpool_ft.tga
gfx/env/whirlpool_lf.tga
gfx/env/whirlpool_rt.tga
gfx/env/whirlpool_up.tga
sprites/grflare2.spr
sprites/grnflare4.spr
sprites/orflare3.spr
sprites/wtflare2.spr