gfx/env/arkiup.tga
gfx/env/arkidn.tga
gfx/env/arkilf.tga
gfx/env/arkirt.tga
gfx/env/arkift.tga
gfx/env/arkibk.tga
sound/weapponstock/sp_elevator.wav
sound/weapponstock/sp_fense.wav
sound/weapponstock/sp_sandfall.wav
sound/weapponstock/sp_windloop.wav
sound/weapponstock/sp_biggun3.wav
sound/weapponstock/sp_explosion_large.wav
sound/weapponstock/sp_rock_fall_little.wav
sound/weapponstock/sp_waterfall1.wav
sound/weapponstock/sp_biggun2.wav
sound/weapponstock/sp_biggun1.wav
models/mdlweaponstock/bush1.mdl
models/mdlweaponstock/bush2.mdl
models/mdlweaponstock/bush3.mdl
models/mdlweaponstock/dnc_antenna1.mdl
models/mdlweaponstock/dnc_wattow.mdl
maps/weaponstock_b1.res